image: python:3.8

stages:
  - lint
  - publish

application-lint:
  stage: lint
    - pip install poetry==1.1.11
    - poetry install
    - poetry run black --check src/
    - poetry run flake8 src/
    - poetry run mypy src/
    - poetry run pydocstyle src/
    - poetry run darglint src/

application-publish:
  stage: publish
  script:
    - pip install poetry==1.1.4
    - poetry config repositories.paaliaq https://gitlab.paaliaq.xyz/api/v4/projects/29/packages/pypi
    - poetry version $CI_COMMIT_TAG
    - poetry publish -r paaliaq --build -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  rules:
    - if: '$CI_COMMIT_TAG'